language: node_js

node_js:
    - lts/*
services: mongodb
install:
    - npm install

script:
    - npm run test

# Allowing travis to cache node_modules directory so it does not need to install full package everytime.
cache: npm

